### ISSUE TITLE
cannot import name resnet

### ISSUE THREAD

**Issue by 21Ansh** [scaelles/DEXTR-PyTorch#7]
When I am trying to run demo.py, I am having following error

Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from networks.dextr import DEXTR
  File "/local/arathore/3D_processing/DEXTR-KerasTensorflow/networks/dextr.py", line 8, in <module>
    from networks import resnet
  File "/local/arathore/3D_processing/DEXTR-KerasTensorflow/networks/resnet.py", line 12, in <module>
    from networks.classifiers import build_pyramid_pooling_module
  File "/local/arathore/3D_processing/DEXTR-KerasTensorflow/networks/classifiers.py", line 10, in <module>
    from networks import resnet
ImportError: cannot import name resnet

**Comment by kmaninis** [comment]
Are you referring to the TensorFlow version of the code? If not, the two repos are mixed, and maybe that is the problem.

**Comment by scaelles** [comment]
I would also make sure that you are using `Python 3.6` as the code may not be compatible with older Python versions.
